const rocketLeaguePlayers = [
  {
    player: "Kelpy",
    irlName: "Kelsan Chisholm",
    school: "Utah",
    record: "4-14",
    goals: 33,
    assists: 22,
    saves: 79,
    shots: 108,
    demos: 40,
    major: "Computer Engineering",
    img: "https://i.ibb.co/rfbNGKVT/Utah-Kelpy-RL.png"
  },
  {
    player: "BranJ",
    irlName: "Bransen Jorgensen",
    school: "Utah",
    record: "4-14",
    goals: 32,
    assists: 24,
    saves: 63,
    shots: 105,
    demos: 57,
    major: "Undeclared",
    img: "https://i.ibb.co/2YnBmy7Y/Utah-Branj-RL.png"
  },
  {
    player: "Hydro",
    irlName: "Trey Johnson",
    school: "Utah",
    record: "4-14",
    goals: 9,
    assists: 10,
    saves: 25,
    shots: 40,
    demos: 16,
    major: "Earth Science",
    img: "https://i.ibb.co/dJBZwDw8/Utah-Hyrdo-RL.png"
  },
  {
    player: "S3TH",
    irlName: "Seth Rushton",
    school: "Utah",
    record: "4-14",
    goals: 7,
    assists: 7,
    saves: 12,
    shots: 17,
    demos: 6,
    major: "Mechanical Engineering",
    img: "https://i.ibb.co/Gvtyq3D2/Utah-Seth.png"
  },
  {
    player: "LlessuR",
    irlName: "Matthew Russell",
    school: "Syracuse",
    record: "13-5",
    goals: 39,
    assists: 17,
    saves: 39,
    shots: 109,
    demos: 105,
    major: "Undeclared",
    img: "https://i.imgur.com/bo8COEg.png"
  },
  {
    player: "TIZRL",
    irlName: "Alex Ortiz-Rosado",
    school: "Syracuse",
    record: "13-5",
    goals: 34,
    assists: 26,
    saves: 60,
    shots: 115,
    demos: 23,
    major: "Undeclared",
    img: "https://i.imgur.com/89g85Mq.png"
  },
  {
    player: "Gababy",
    irlName: "Gabriel Goodwin",
    school: "Syracuse",
    record: "13-5",
    goals: 24,
    assists: 37,
    saves: 55,
    shots: 94,
    demos: 69,
    major: "Business management",
    img: "https://i.imgur.com/VngrJMN.png"
  },
  {
    player: "gaines",
    irlName: "Ilhan Ozdil",
    school: "Ohio State",
    record: "8-10",
    goals: 39,
    assists: 31,
    saves: 78,
    shots: 140,
    demos: 66,
    major: "Undeclared",
    img: "https://i.ibb.co/N6rDmdxc/OSU-Rocket-League-Gaines02.png"
  },
  {
    player: "Bungo",
    irlName: "Andrew Nikolai",
    school: "Ohio State",
    record: "8-10",
    goals: 35,
    assists: 27,
    saves: 76,
    shots: 145,
    demos: 26,
    major: "Undeclared",
    img: "https://i.ibb.co/M5CxLqQb/Rocket-League-Bungo02.png"
  },
  {
    player: "danwad",
    irlName: "Nick Danforth",
    school: "Ohio State",
    record: "8-10",
    goals: 22,
    assists: 18,
    saves: 35,
    shots: 70,
    demos: 22,
    major: "Undeclared",
    img: "https://i.ibb.co/WN9Vfnjg/Rocket-League-Danwad02.png"
  },
  {
    player: "CJ",
    irlName: "Christopher Wood",
    school: "Ohio State",
    record: "8-10",
    goals: 18,
    assists: 13,
    saves: 30,
    shots: 58,
    demos: 35,
    major: "Undeclared",
    img: null
  },
  {
    player: "Mintzy",
    irlName: "Kade Wickham",
    school: "Nebraska",
    record: "6-12",
    goals: 41,
    assists: 27,
    saves: 79,
    shots: 118,
    demos: 65,
    major: "Marketing and Management",
    img: "https://i.imgur.com/tvLX9G0.png"
  },
  {
    player: "creedrl",
    irlName: "Hugh Strumberger",
    school: "Nebraska",
    record: "6-12",
    goals: 34,
    assists: 32,
    saves: 69,
    shots: 134,
    demos: 44,
    major: "Computer Science",
    img: "https://i.imgur.com/kHIdwQh.png"
  },
  {
    player: "Promising RL",
    irlName: "Benjamin Priest",
    school: "Nebraska",
    record: "6-12",
    goals: 27,
    assists: 26,
    saves: 90,
    shots: 104,
    demos: 48,
    major: "Accounting",
    img: "https://i.imgur.com/siZ25YV.jpeg"
  },
  {
    player: "CyanDelta",
    irlName: "Brody Knaak",
    school: "Nebraska",
    record: "6-12",
    goals: 2,
    assists: 1,
    saves: 3,
    shots: 4,
    demos: 8,
    major: "Viola Performance / Mechanical Engineering",
    img: "https://i.imgur.com/j2y0GKc.png"
  },
  {
    player: "Rad",
    irlName: "Braden Raddatz",
    school: "Minnesota",
    record: "5-13",
    goals: 38,
    assists: 20,
    saves: 73,
    shots: 119,
    demos: 75,
    major: "Mechanical Engineering",
    img: "https://i.imgur.com/c0zCMwA.png"
  },
  {
    player: "WarPai",
    irlName: "Adan Alatoma",
    school: "Minnesota",
    record: "5-13",
    goals: 30,
    assists: 18,
    saves: 91,
    shots: 118,
    demos: 44,
    major: "Aerospace Engineering",
    img: "https://i.imgur.com/Edzai4k.png"
  },
  {
    player: "mralexplas",
    irlName: "Alex Pupp",
    school: "Minnesota",
    record: "5-13",
    goals: 20,
    assists: 20,
    saves: 50,
    shots: 60,
    demos: 67,
    major: "Computer science",
    img: "https://i.ibb.co/5WzfvLJf/RAD-braden-raddatz.png"
  },
  {
    player: "Alphy1",
    irlName: "Alphonce Ayega",
    school: "Minnesota",
    record: "5-13",
    goals: 9,
    assists: 4,
    saves: 25,
    shots: 22,
    demos: 7,
    major: "Computer Science",
    img: "https://i.imgur.com/QE9we8n.png"
  },
  {
    player: "opp_bomb",
    irlName: "Connor Neiheisel",
    school: "Michigan State",
    record: "14-4",
    goals: 40,
    assists: 16,
    saves: 44,
    shots: 125,
    demos: 80,
    major: "Computer Science",
    img: "https://i.imgur.com/JEhBzqK.png"
  },
  {
    player: "Morveu",
    irlName: "Christian Riegert",
    school: "Michigan State",
    record: "14-4",
    goals: 27,
    assists: 30,
    saves: 41,
    shots: 95,
    demos: 34,
    major: "Digital Storytelling",
    img: "https://i.imgur.com/J24vIrn.png"
  },
  {
    player: "nock",
    irlName: "Nicholas Dowdican",
    school: "Michigan State",
    record: "14-4",
    goals: 21,
    assists: 18,
    saves: 36,
    shots: 67,
    demos: 45,
    major: "Finance",
    img: "https://i.ibb.co/SRRZf8v/Nock.png"
  },
  {
    player: "Druee",
    irlName: "Andrew Prill",
    school: "Michigan State",
    record: "14-4",
    goals: 12,
    assists: 12,
    saves: 24,
    shots: 48,
    demos: 19,
    major: null,
    img: null
  },
  {
    player: "sibs",
    irlName: "Sahib Dhillon",
    school: "Michigan State",
    record: "14-4",
    goals: 5,
    assists: 5,
    saves: 12,
    shots: 13,
    demos: 12,
    major: null,
    img: null
  },
  {
    player: "Alpacca",
    irlName: "Kyle Maddox",
    school: "Kansas",
    record: "7-11",
    goals: 27,
    assists: 21,
    saves: 42,
    shots: 83,
    demos: 62,
    major: "Mechanical Engineering",
    img: "https://i.imgur.com/zsZoRff.png"
  },
  {
    player: "meve",
    irlName: "Maddox Stueve",
    school: "Kansas",
    record: "7-11",
    goals: 24,
    assists: 18,
    saves: 71,
    shots: 84,
    demos: 25,
    major: "Business",
    img: "https://i.imgur.com/MvstQiK.png"
  },
  {
    player: "Swift",
    irlName: "Landon Swift",
    school: "Kansas",
    record: "7-11",
    goals: 19,
    assists: 19,
    saves: 44,
    shots: 75,
    demos: 55,
    major: "Psychology",
    img: "https://i.imgur.com/isAKpTy.png"
  },
  {
    player: "durtho",
    irlName: "Emiliano Flores",
    school: "Boise State",
    record: "15-3",
    goals: 69,
    assists: 39,
    saves: 72,
    shots: 205,
    demos: 56,
    major: "Health Studies",
    img: "https://i.imgur.com/5rPBia8.png"
  },
  {
    player: "WUZYWRLD",
    irlName: "Cade Hall",
    school: "Boise State",
    record: "15-3",
    goals: 64,
    assists: 43,
    saves: 71,
    shots: 212,
    demos: 73,
    major: "Psychology",
    img: "https://i.imgur.com/QehceP8.png"
  },
  {
    player: "prstn",
    irlName: "Preston Ferrante",
    school: "Boise State",
    record: "15-3",
    goals: 52,
    assists: 58,
    saves: 77,
    shots: 169,
    demos: 51,
    major: "Business",
    img: "https://i.imgur.com/Hmi9f4W.png"
  },
  {
    player: "Andy",
    irlName: "Andrew Nolan",
    school: "Baylor",
    record: "18-0",
    goals: 58,
    assists: 44,
    saves: 71,
    shots: 144,
    demos: 38,
    major: "Accounting",
    img: "https://i.imgur.com/LV3CERv.png"
  },
  {
    player: "hockser",
    irlName: "Colby James",
    school: "Baylor",
    record: "18-0",
    goals: 46,
    assists: 40,
    saves: 51,
    shots: 131,
    demos: 48,
    major: "Mechanical Engineering",
    img: "https://i.imgur.com/Ka2svlb.png"
  },
  {
    player: "jt25rl",
    irlName: "Joseph Tornari",
    school: "Baylor",
    record: "18-0",
    goals: 26,
    assists: 19,
    saves: 14,
    shots: 71,
    demos: 44,
    major: null,
    img: "https://i.ibb.co/CKx6Pt4j/si-Z25-YV-no-bg-c4csio0k.png"
  },
  {
    player: "Zineel",
    irlName: "Kadin Zineelabidine",
    school: "Baylor",
    record: "18-0",
    goals: 14,
    assists: 15,
    saves: 13,
    shots: 47,
    demos: 16,
    major: "Undeclared",
    img: "https://i.imgur.com/YZRyqZg.png"
  }
];

export default rocketLeaguePlayers;
